- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install installation dependencies
  ansible.builtin.apt:
    pkg: 
    - debian-keyring
    - debian-archive-keyring
    - apt-transport-https
    state: present

- name: Check if Caddy keyring is installed
  stat:
    path: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  register: keyring_inst

- name: Download  keyring
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /tmp/gpg.key
  when: not keyring_inst.stat.exists

- name: Install Caddy keyring
  ansible.builtin.command: gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg /tmp/gpg.key
  when: not keyring_inst.stat.exists

- name: Check if Caddy source list is installed
  stat:
    path: /etc/apt/sources.list.d/caddy-stable.list
  register: caddy_s_inst

- name: Download source list
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    dest: /tmp/debian.deb.txt
  when: not caddy_s_inst.stat.exists

- name: Copy source list
  ansible.builtin.command: cp /tmp/debian.deb.txt /etc/apt/sources.list.d/caddy-stable.list
  when: not caddy_s_inst.stat.exists
  
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Caddy package
  ansible.builtin.apt:
    name: caddy
    state: present
  
- name: Check if Caddyfile is installed
  stat:
    path: /etc/caddy/Caddyfile
  register: caddy_file_inst

- name: Copy Caddyfile to /etc/caddy
  template:
    src: Caddyfile
    dest: /tmp/Caddyfile
  when: no caddy_file_inst.stat.exists


- name: Start and enable Caddy
  service:
    name: caddy
    state: started
    enabled: yes
